---
#System Settings
php_modules: [ 'php-curl', 'php-gd', 'php-mbstring', 'php-xml', 'php-xmlrpc', 'php-soap', 'php-intl', 'php-zip' ]

#MySQL Settings
mysql_root_password: "R00t_passwd"
mysql_db: "wordpress"
mysql_user: "vincent"
mysql_password: "Passwd123"

#HTTP Settings
http_host: "ryjel"
http_conf: "ryjel.conf"
http_port: "80"
